import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../domain/training_session.dart';

class PdfService {
  static Future<void> generateRoutineOrder(TrainingSession session, CadetElement element) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('ROUTINE ORDER / TRAINING PLAN', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
                  pw.Text(DateFormat('dd MMM yyyy').format(session.date)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Text('TYPE: ${session.type.name.toUpperCase()}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 10),
            pw.Divider(),
            
            // Administrative Details
            pw.SizedBox(height: 10),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('DUTY OFFICER: ${session.dutyOfficer ?? 'TBD'}', style: const pw.TextStyle(fontSize: 10)),
                    pw.Text('DUTY NCO: ${session.dutyNCO ?? 'TBD'}', style: const pw.TextStyle(fontSize: 10)),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text('DRESS: ${session.dress ?? 'TBD'}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                  ],
                ),
              ],
            ),
            
            if (session.announcements != null && session.announcements!.isNotEmpty) ...[
              pw.SizedBox(height: 10),
              pw.Container(
                padding: const pw.EdgeInsets.all(8),
                decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('ANNOUNCEMENTS:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8)),
                    pw.Text(session.announcements!, style: const pw.TextStyle(fontSize: 9)),
                  ],
                ),
              ),
            ],
            
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.SizedBox(height: 20),
            
            // Matrix Table(s) - Split into chunks of 3 periods to fit on page
            for (int i = 0; i < session.numPeriods; i += 3) ...[
              if (i > 0) pw.SizedBox(height: 20),
              pw.Table(
                border: pw.TableBorder.all(),
                columnWidths: {
                  0: const pw.FixedColumnWidth(60),
                },
                children: [
                  pw.TableRow(
                    children: [
                      pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text(element == CadetElement.army ? 'STAR LEVEL' : (element == CadetElement.sea ? 'PHASE' : 'LEVEL'), style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      for (int p = i; p < i + 3 && p < session.numPeriods; p++)
                        pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text('PERIOD ${p + 1}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                    ],
                  ),
                  for (var phase in Phase.values)
                    pw.TableRow(
                      children: [
                        pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text(phase.getLabel(element), style: const pw.TextStyle(fontSize: 10))),
                        for (int p = i; p < i + 3 && p < session.numPeriods; p++)
                          _buildPdfSlot(session.matrix[phase]![p]),
                      ],
                    ),
                ],
              ),
            ],
            
            pw.SizedBox(height: 40),
            pw.Divider(),
            pw.Text('Generated by Training Officer Tool - ${element.label}', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Training_Plan_${DateFormat('yyyyMMdd').format(session.date)}.pdf',
    );
  }

  static Future<void> generateTrainingPlan(List<TrainingSession> sessions, String title, CadetElement element) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(title.toUpperCase(), style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
                  pw.Text('Exported: ${DateFormat('dd MMM yyyy').format(DateTime.now())}'),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              columnWidths: {
                0: const pw.FixedColumnWidth(80), // Date
                1: const pw.FixedColumnWidth(60), // Type
                2: const pw.FlexColumnWidth(1),   // P1
                3: const pw.FlexColumnWidth(1),   // P2
                4: const pw.FlexColumnWidth(1),   // P3
                5: const pw.FlexColumnWidth(1),   // P4
              },
              children: [
                // Header Row
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                  children: [
                    _buildCell('DATE', isHeader: true),
                    _buildCell('TYPE', isHeader: true),
                    for (var phase in Phase.values)
                      _buildCell(phase.getLabel(element).toUpperCase(), isHeader: true),
                  ],
                ),
                // Data Rows
                for (var session in sessions)
                  pw.TableRow(
                    children: [
                      _buildCell(DateFormat('dd MMM yyyy').format(session.date)),
                      _buildCell(session.type.name.toUpperCase(), fontSize: 8),
                      for (var phase in Phase.values)
                        _buildPhaseSummaryCell(session.matrix[phase] ?? []),
                    ],
                  ),
              ],
            ),
            
            pw.SizedBox(height: 40),
            pw.Divider(),
            pw.Text('Generated by Training Officer Tool - ${element.label}', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: '${title.replaceAll(' ', '_')}.pdf',
    );
  }

  static pw.Widget _buildCell(String text, {bool isHeader = false, double fontSize = 10}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          fontSize: fontSize,
        ),
      ),
    );
  }

  static pw.Widget _buildPhaseSummaryCell(List<LessonSlot> slots) {
    final eocodes = slots.where((s) => s.eoCode != null).map((s) => s.eoCode!).toList();
    
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          if (eocodes.isEmpty)
            pw.Text('---', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey))
          else
            for (var code in eocodes)
              pw.Text(code, style: const pw.TextStyle(fontSize: 9)),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfSlot(LessonSlot slot) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(4),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(slot.eoCode ?? 'EMPTY', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
          if (slot.title != null) 
            pw.Text(slot.title!, style: const pw.TextStyle(fontSize: 8), maxLines: 2),
          if (slot.instructor != null) 
            pw.Text('Instr: ${slot.instructor}', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey)),
          if (slot.location != null) 
            pw.Text('Loc: ${slot.location}', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey)),
        ],
      ),
    );
  }
}
