import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../domain/training_session.dart';

class PdfService {
  static Future<void> generateRoutineOrder(TrainingSession session) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('ROUTINE ORDER / TRAINING PLAN', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
                    pw.Text(DateFormat('dd MMM yyyy').format(session.date)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text('TYPE: ${session.type.name.toUpperCase()}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Divider(),
              pw.SizedBox(height: 20),
              
              // Matrix Table
              pw.Table(
                border: pw.TableBorder.all(),
                children: [
                  pw.TableRow(
                    children: [
                      pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text('PHASE', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text('PERIOD 1', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text('PERIOD 2', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text('PERIOD 3', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                    ],
                  ),
                  for (var phase in Phase.values)
                    pw.TableRow(
                      children: [
                        pw.Padding(padding: pw.EdgeInsets.all(4), child: pw.Text(phase.label)),
                        for (var slot in session.matrix[phase]!)
                          pw.Padding(
                            padding: pw.EdgeInsets.all(4),
                            child: pw.Column(
                              crossAxisAlignment: pw.CrossAxisAlignment.start,
                              children: [
                                pw.Text(slot.eoCode ?? 'EMPTY', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
                                if (slot.title != null) pw.Text(slot.title!, style: pw.TextStyle(fontSize: 8)),
                                if (slot.instructor != null) pw.Text('Instr: ${slot.instructor}', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
                                if (slot.location != null) pw.Text('Loc: ${slot.location}', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
                              ],
                            ),
                          ),
                      ],
                    ),
                ],
              ),
              
              pw.Spacer(),
              pw.Divider(),
              pw.Text('Generated by Training Officer Tool - Sea Cadets Canada', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Training_Plan_${DateFormat('yyyyMMdd').format(session.date)}.pdf',
    );
  }
}
